---
version: "{build}"
skip_tags: true
clone_depth: 10

init:
  # To avoid duplicated executables in PATH, see https://github.com/ruby/spec/pull/468
  - set PATH=C:\ruby%RUBY_VERSION%\bin;C:\msys64\usr\bin;C:\Program Files\7-Zip;C:\Program Files\AppVeyor\BuildAgent;C:\Program Files\Git\cmd;C:\Windows\system32;C:\Program Files;C:\Windows
  # Loads trunk build
  - if %ruby_version%==_trunk (
      appveyor DownloadFile %APPVEYOR_URL%/api/projects/MSP-Greg/ruby-loco/artifacts/ruby_trunk.7z -FileName C:\ruby_trunk.7z &
      7z x C:\ruby_trunk.7z -oC:\ruby_trunk
    )

install:
  - ruby --version
  - gem --version
  - gem install bundler --version "~> 1.15.1" --no-ri --no-rdoc
  - bundle install --jobs=3 --retry=3

test_script:
  - rake -rdevkit test
  - rake package
  - gem install --local pkg/gem-compiler-*.gem

on_finish:
  - ruby --version
  - gem --version

build: off

environment:
  matrix:
    - ruby_version: "21"
    - ruby_version: "21-x64"
    - ruby_version: "22"
    - ruby_version: "22-x64"
    - ruby_version: "23"
    - ruby_version: "23-x64"
    - ruby_version: "24"
    - ruby_version: "24-x64"
    - ruby_version: "_trunk"
